"""Init migration

Revision ID: d623dbed6844
Revises: 
Create Date: 2023-09-05 21:11:17.953456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd623dbed6844'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enchantment = op.create_table('enchantment',
    sa.Column('enchantment_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('enchantment_level')
    )
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    quality = op.create_table('quality',
    sa.Column('quality_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('quality_level')
    )
    op.create_table('item',
    sa.Column('item_type_id', sa.String(), nullable=False),
    sa.Column('albion_id', sa.Integer(), nullable=True),
    sa.Column('enchantment_level', sa.Integer(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enchantment_level'], ['enchantment.enchantment_level'], ),
    sa.PrimaryKeyConstraint('item_type_id')
    )
    op.create_table('sales_by_day',
    sa.Column('item_type_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quality_level', sa.Integer(), nullable=False),
    sa.Column('sold_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('sold', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['item_type_id'], ['item.item_type_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.ForeignKeyConstraint(['quality_level'], ['quality.quality_level'], ),
    sa.PrimaryKeyConstraint('item_type_id', 'location_id', 'quality_level', 'sold_date')
    )
    # ### end Alembic commands ###

    # ### seed data
    op.bulk_insert(quality,[
            {'quality_level': '1'},
            {'quality_level': '2'},
            {'quality_level': '3'},
            {'quality_level': '4'},
            {'quality_level': '5'}
        ] )

    op.bulk_insert(enchantment, [
        {'enchantment_level': '0'},
        {'enchantment_level': '1'},
        {'enchantment_level': '2'},
        {'enchantment_level': '3'},
        {'enchantment_level': '4'}
    ])
    # ### end of seed data


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_by_day')
    op.drop_table('item')
    op.drop_table('quality')
    op.drop_table('location')
    op.drop_table('enchantment')
    # ### end Alembic commands ###
